### ISSUE TITLE
Unsupported operation: Isolate.packageConfig

### ISSUE THREAD

**Issue by mutairibassam** [AymanProjects/flutter-flavorz#22]
Facing an error when I execute `flutter test`

Error reproduce:
1- clone master branch `git clone https://github.com/AymanProjects/dart-flavorz.git`
2- go to root project & run `flutter clean && flutter pub get`
3- run `flutter test`
4- error will occurs and test will fail.

Not sure if this only happens for iOS users or not. @ikema77 can you test from your end and verify.

**Comment by AymanProjects** [comment]
@mutairibassam 
Please pull the latest changes in the Tests Branch https://github.com/AymanProjects/flutter-flavorz/tree/breakdown-unit-tests 
Then run `dart test`
And see if the error still appears
